theme: jekyll-theme-modernist
show_downloads: true
github:
  zip_url: https://github.com/Carlover101/AutoMCServer/archive/refs/heads/linux.zip
  tar_url: https://github.com/Carlover101/AutoMCServer/archive/refs/heads/linux.tar.gz
