import time

print("The Server.properties file changes how the server runs and generates worlds.")
time.sleep(2)
YD = input("Would you like to customize this file or leave it as the default values? (Custom/Default)")

if YD.lower() == "Default":
  print("Setting to default...")
  time.sleep(1)
  print("Done")
  exit()
  
elif YD.lower() == "Custom":
  sprot = input("How large would you like the player spawn protection to be? (16 is default) ")
  mtick = input("What would you like the max tick timeout to be? (0 = never; 60000 is default) ")
  qport = input("Which port would you like to run the query on? (25565 is default) ")
  genst = input("What generators setting would you like to add? (leave blank if you want to skip) ")
  syncw = input("What would you like to set sync-chunk-writes to? (true/false; default is true) ")
  fgame = input("Would you like to force the gamemode? (true/false; default is false) ")
  alnet = input("Would you like to enable the nether? (true/false; default is true) ")
  enwht = input("Would you like to enfore the whitelist? (true/false; default is false) ")
  gamem = input("What would like to set the gamemode to? (survival/creatove/adventure; defualt is survival) ")
  bctop = input("Would you like to broadcast the console commands to operators? (true/false; default is true) ")
  enque = input("Would you like to enable the query? (true/false; default is false) ")
  pidlt = input("What would you like to set the idle timeout to be? (0 = never; default is 0) ")
  diffc = input("What would you like to set the difficulty to? (easy/normal/hard; default is easy) ")
  spmon = input("Would you like to enable monster spawning? (true/false; default is true) ")
  brtop = input("Would you like to broadcast rcon to ops? (true/false; default is true) ")
  operm = input("What would like to set the operator permission level to? (1/2/3/4; default is 4) ")
  enpvp = input("Would you like to enable pvp? (true/false; default is true) ")
  enbrp = input("What would you like to set the entity broadcast range percentage to? (0-100; default is 100) ")
  ensnp = input("Would you like to enable snoopers? (true/false) ")
  lvlty = input("What would like to set the level type to? (flat/default; default is default) ")
  hrdcr = input("Would you like to set the world to hardcore? (true/false; default is false) ")
  estat = input("Would you like to enable status? (true/false; default is true) ")
  encmb = input("Would you like to enable command blocks? (true/false; default is false) ")
  mxplr = input("What would you like to set the max player count to? (0-9999999; default is 20) ")
  netct = input("What would you like to set the network compression threshold to? (0-512; default is 256) ")
  ressh = input("What would you like to set the resource pack sha1 to? (paste here; default is blank) ")
  mxwsz = input("What would you like to set the mac world size to? (0-29999984; default is 29999984) ")
  fnprl = input("What would you like to set the function permission level to? (1-2; default is 2) ")
  rcnpt = input("What would you like to set the rcon port to? (default is 25575) ")
  srvpt = input("What would you like to set the server port to? (default is 25565) ")
  debug = input("Would you like to turn on debug? (true/false; default is true) ")
  srvip = input("What would like to set the server ip address to? (if you do not know, leave this blank) ")
  spnpc = input("Would you like to enable the spawning of npcs? (true/false; default is true) ")
  alflt = input("Would you like to enable flight? (true/false; default is false) ")
  lvlnm = input("What would you like to name the world file? (default is world) ")
  vdist = input("What would you like to set the player view distance to? (2-64; default is 10) ")
  respk = input("What would you like to set the resource pack to? (paste a link here; default is blank) ")
  spnan = input("Would you like to turn animal spawning on? (true/false; default is true) ")
  wtlst = input("Would you like to enable whitelist? (true/false; default is false) ")
  rconp = input("What would you like to set the rcon password to? (paste or type here; default is blank) ")
  genst = input("Would you like to turn structure generation on? (true/false; default is true) ")
  mxbhi = input("What would you like to set the maximum build hight to? (0-256; default is 256) ")
  onmde = input("Would you like to set online mode on? (true/false; default is true) ")
  lvlsd = input("What would you like to set the world seed to? (paste here; default is blank) ")
  usnts = input("Would you like to use native transport? (true/false; default is true) ")
  prepc = input("Would you like to prevent proxy connections? (true/false; default is false) ")
  enjmx = input("Would you like to enable jmx monitoring? (true/false; default is false) ")
  enrcn = input("Would you like to enable rcon? (true/false; default is false) ")
  smotd = input("What would you like to set the message of the day to? (paste or type it here; default is 'A Minecraft Server') ")
  
sp = open("server.properties","w+")

sp.write("#Minecraft server properties\n")

